### ISSUE TITLE
New topics can't be posted

### ISSUE THREAD

**Issue by Serinus1** [bravecollective/forums#77] opened 2014-04-08 18:50 UTC
Replies seem to work, but new threads can't be created.

**Comment by jboning** [comment] 2014-04-08 19:26
Is this in a forum where you have the moderator permission but not the write permission? Exactly this is what led me to create #75.

**Comment by Serinus1** [comment] 2014-04-08 19:35
Turns out it's this.  Still an issue, just not the one I thought it was.  Still, the title is useful for anyone running into this.

![image](https://cloud.githubusercontent.com/assets/3591696/2648223/df57fa84-bf54-11e3-9670-83e572ae1b4c.png)

**Comment by jboning** [comment] 2014-04-08 19:38
Oh okay. Well, already tracked in #44, fixed by #71.

**Comment by jboning** [comment] 2014-04-24 22:55
closing as dupe of #44 (and also #71 has been merged)

**Closed as completed by jboning** 2014-04-24 22:55 UTC
