### ISSUE TITLE
Make 'Start Discussion' buttons unambiguous and foolproof

### ISSUE THREAD

**Issue by csw** [bravecollective/forums#78] opened 2014-04-08 19:26 UTC
It appears from [this forum thread](https://forums.bravecollective.net/a/534270ae58b7000356671d41) and my own experience that the current 'Start Discussion' button behavior, with the submission button at the top of the form and another, subtly different, one that toggles form visibility below, is difficult to use correctly. I've lost at least one post because I hit the submit button under the form, just like on this bug-reporting form and practically every other form on the web.

I would suggest moving or duplicating the 'Start Discussion' button that submits to the bottom of the form, and hiding the one that toggles the new post form while the form is active. This would make it easy and natural to find the correct button and impossible to use the wrong one by mistake.

At a minimum, some kind of warning when hiding the form with un-submitted content would be good.

**Comment by jboning** [comment] 2014-04-08 19:28
This is a duplicate of #44, which is fixed by #71.

**Comment by jboning** [comment] 2014-04-24 22:55
closing as dupe of #44 (and also #71 has been merged)

**Closed as completed by jboning** 2014-04-24 22:55 UTC
